### ISSUE TITLE
Possibility small seconds & Original firmware 

### ISSUE THREAD

**Issue by JayJay1989** [trip5/EspHome-Led-PixelClock#2]
Is it possible to add the small seconda  (and possibility for the animation when digits changes)

I contacted the seller to get the original firmware. At first it was not possible, but because I needed to set a static IP they gave me all the files

[Y4025.zip](https://github.com/trip5/EspHome-Led-PixelClock/files/13799520/Y4025.zip)

**Comment by JayJay1989** [comment]
The zip above includes:
- Gerber files
- compiled firmware
- ino file

**Comment by trip5** [comment]
Woah, that's cool.  I'm surprised the manufacturer was so open to send all that.  That looks like Arduino IDE firmware.

Also, lol, knowing China, your source could be either the original guy who designed it, per his channel here: https://www.youtube.com/@hacklabs/videos  OR more likely, someone took his idea and mass-manufactured it for cheap.

Do you mean fractions of a second?  I doubt the hardware can keep up but you can try: https://stackoverflow.com/questions/7588511/format-a-datetime-into-a-string-with-milliseconds

You should update `update_interval: 1s` to 100ms or 200ms and see if the firmware can keep up... I don't think the timing of the date or Home Assistant messages depend on that part.  I wouldn't go any more frequent than 100ms for risk of the clock crashing, though.

Or do you just mean can you add seconds to 12-hour time?  My default 24-hour time already includes it.  Yes, of course, but you'd have to ditch the AM/PM indicator.

As for the animation... No.  I'd have to sacrifice the reliance on `strftime` which is a string.   His firmware uses numbers for each individual digit.  I've already done such a routine with my other LED clock and the ability to display different time formats using strftime strings will be completely lost.

One reason I'm using the current method is because at some point I will work in the ability to substitute characters so you will have the ability to display Months, Days, AM & PM in your local language.

**Comment by JayJay1989** [comment]
i meant the font size of the seconds smaller, more like the original firmware.

**Comment by trip5** [comment]
Huh.  Maybe?  I can chew on that a bit... let me see if it's feasible and worth it.
