### ISSUE TITLE
Alarm Function

### ISSUE THREAD

**Issue by modem7** [trip5/EspHome-Led-PixelClock#4]
Heya, 

Given that this is an ESP based project, would you know of any way of modifying this to have an alarm clock function at all? 

I'm aware that this particular unit probably doesn't have a speaker etc, but I'm just looking at expansion ideas currently!

Cheers!

**Comment by modem7** [comment]
Hmmm - looking at this https://www.printables.com/model/1003981-alarm-clock-esphome-d1-mini/files there may be a way of utilising an external HA alarm function by utilising other speakers etc.

**Comment by trip5** [comment]
Sure there are ways of expanding these units physically.  I already did but haven't posted details of it yet because it's kind of messed-up to be soldering wires directly to the back of a board like this.  On one of mine (a large one, the smaller one has almost no room to work with), I added an XH2.54 female port wired directly to GPIOs 0, 1, 3, and 12 of the ESP12, and the power regulator at GND and 3V3.  But, the only real "free" GPIO is 12 (GPIO 0 is the button, 1 is TX, 3 is RX).

And yes, you could add alarms to the YAML too.  This clock YAML files were originally drawn from the [EspHome-Led-Clock](https://github.com/trip5/EspHome-Led-Clock) and I put a lot of the same routines in both.  It uses Nokia-styl;e ringtones.  It wouldn't be hard to look at the code for both and just put in the missing bits.  My code is pretty well-commented.

But, the speaker modules of ESPHome actually use a non-significant amount of memory.  The fonts do, too.  While playing with my expansion, I noticed adding anything that wasn't already there (in my case it was an RF receiver) meant I had to remove things too or the clock would crash (like reducing from 2 fonts to 1 and removing un-needed glyphs). My YAML already pushes the poor ESP12 to its limit - which is why I had to split the YAMLs in 2 flavors anyway.

You're welcome to continue this conversation but if all you're looking for is an alarm, the XY-Clocks already have one built onto them, and they're much cheaper (and my YAMLs support them)... or go full-out and get an Ulanzi TC-001 and try [EHMTXv2](https://github.com/lubeda/EspHoMaTriXv2).

**Comment by modem7** [comment]
Sorry for my late reply, I missed the notification.

Thank you so much for the indepth reply, I think you've covered every question I could have on that subject and why it'd be somewhat difficult to do so.

Sincerely appreciate it, I'll have a think about the best way forward!
